name: interval_halving_method
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:

  flutter_bloc: ^9.1.1

  # Core UI & icons
  cupertino_icons: ^1.0.8

  # Localization
  easy_localization: ^3.0.7+1


  # Flutter SDK (framework)
  flutter:
    sdk: flutter

  # Code generation module
  gen:
    path: module/gen

  # Router
  go_router: ^16.0.0

  # Utilities
  image_picker: ^1.1.2
  logger: ^2.6.0
  math_expressions: ^2.7.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linter & static analysis
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/langs/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800